name: visual_editor
description: A rich text editor supporting mobile and web (Demo App @ visualspace.app)
version: 0.0.1
homepage: https://visualspace.app
repository: https://github.com/visual-space/visual-editor

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.17.2
  flex_color_picker: ^3.4.1
  flutter_keyboard_visibility: ^5.4.1
  image_picker: ^1.0.4
  photo_view: ^0.14.0
  quiver: ^3.2.1
  string_validator: ^1.0.2
  url_launcher: ^6.2.1
  video_player: ^2.8.1
  characters: ^1.3.0
  youtube_player_flutter: ^8.1.2
  diff_match_patch: ^0.4.1
  i18n_extension: ^9.0.2
  device_info_plus: ^9.1.0
  google_fonts: ^6.1.0 

  

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
